/* Local document intake. No provider, credentials or patient data is sent remotely. */
(()=>{
 const $=id=>document.getElementById(id),core=PiDemoCore;
 let sources=[],draft=null,templates=[],noteSource='Doctor notes / transcript';
 const ready=fetch(PiExtension.runtime.getURL('reports.json')).then(r=>r.json()).then(value=>{templates=value;for(const t of templates){const option=document.createElement('option');option.value=t.id;option.textContent=t.title;$('template').append(option);}$('template').value='soap';});
 let processing=false;
 const localHeaders=()=>({'X-Pi-Token':$('local-token').value.trim()});
 async function request(path,options={}){if(!$('local-token').value.trim())throw new Error('Start the Mac service and enter its pairing code.');let response;try{response=await fetch('http://127.0.0.1:8765'+path,{...options,headers:{...localHeaders(),...options.headers}});}catch{throw new Error('Cannot connect to the local service. Start Start.command on your Mac and reload the extension after updating its permissions.');}const value=await response.json();if(!response.ok)throw new Error(value.error||'Local service request failed.');return value;}
 async function job(path,options){if(processing)throw new Error('Wait for the current local job.');processing=true;for(const id of ['ai-generate','transcribe-audio','generate','source-files','add-notes','template','case-label','encounter','report-file','review-draft'])$(id).disabled=true;try{const {job_id}=await request(path,options);for(;;){await new Promise(resolve=>setTimeout(resolve,1500));const value=await request('/jobs/'+encodeURIComponent(job_id));$('local-status').textContent=value.stage||'Processing locally…';if(value.status==='error')throw new Error(value.error);if(value.status==='complete')return value.result;}}finally{processing=false;for(const id of ['ai-generate','transcribe-audio','generate','source-files','add-notes','template','case-label','encounter','report-file','review-draft'])$(id).disabled=false;}}
 const safe=fn=>async()=>{try{await ready;await fn();}catch(e){$('result').textContent=e.message;$('result').className='error';}};
 const element=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
 function invalidate(){if(draft){draft.status='draft';delete draft.reviewed_at;}$('confirm-review').checked=false;window.dispatchEvent(new Event('pi-draft-edited'));$('draft-status').textContent='DRAFT · review required';}
 function render(){
  $('draft-fields').replaceChildren();if(!draft)return;
  const template=templates.find(t=>t.id===draft.template_id);
  for(const f of template.fields){const value=draft.fields[f.id],section=element('section'),label=element('label',f.label),input=element('textarea');input.value=value.text;input.dataset.field=f.id;input.addEventListener('input',()=>{value.text=input.value;value.edited=true;invalidate();});label.append(input);section.append(label);
   if(value.conflict&&!value.resolved){section.append(element('p','Conflicting source passages: select a passage or edit a reconciled statement.'));
    for(const candidate of value.candidates){const details=element('details');details.append(element('summary',candidate.citations.map(c=>`${c.source_name} · page ${c.page}`).join('; ')),element('p',candidate.text));const choose=element('button','Use this source passage');choose.addEventListener('click',()=>{value.text=candidate.text;value.citations=structuredClone(candidate.citations);value.resolved=true;invalidate();render();});details.append(choose);section.append(details);}
    const resolve=element('button','Resolve using my edited statement');resolve.addEventListener('click',()=>{if(!value.text.trim())return;value.resolved=true;value.citations=value.candidates.flatMap(c=>c.citations);invalidate();render();});section.append(resolve);
   }
   for(const c of value.citations){const details=element('details'),quote=element('p',c.quote);quote.className='source-quote';details.append(element('summary',`${c.source_name} · page ${c.page}, line ${c.line}`),quote);section.append(details);}
   if(!value.text) section.append(element('p','No matching passage. Complete this section from the sources or explain why it is not applicable.'));
   $('draft-fields').append(section);
  }
  const s=core.stats(draft);$('draft-status').textContent=`${draft.status==='reviewed_unsigned'?'Reviewed locally · unsigned':'DRAFT'} · ${s.filled}/${s.total} sections · ${s.conflicts} unresolved conflicts`;
 }
 function renderSources(){ $('sources').replaceChildren();sources.forEach(source=>{const d=element('details');d.append(element('summary',`${source.name} · ${source.pages.length} page(s)`));const p=element('pre',source.pages.map((page,i)=>`PAGE ${i+1}\n${page}`).join('\n\n'));p.className='source-quote';d.append(p);$('sources').append(d);});}
 function add(name,pages){if(sources.length>=20)throw new Error('Limit: 20 source documents.');if(sources.flatMap(s=>s.pages).join('').length+pages.join('').length>2000000)throw new Error('Split large cases into selected encounter documents.');sources.push({id:crypto.randomUUID(),name,pages});invalidate();renderSources();}
 $('connect-local').addEventListener('click',safe(async()=>{const status=await request('/health');$('local-status').textContent=status.model_ready?`Connected · ${status.model} ready · transcription model ${status.transcription}`:`Service connected, but ${status.model} is missing. Finish Install.command.`;}));
 $('transcribe-audio').addEventListener('click',safe(async()=>{const file=$('audio-file').files[0];if(!file)throw new Error('Choose a recording first.');if(file.size>100*1024*1024)throw new Error('Recording limit: 100 MB.');if($('notes').value.trim()&&!confirm('Replace the notes box with this transcript? Add existing notes first to keep them.'))return;const suffix='.'+file.name.toLowerCase().split('.').pop();const result=await job('/transcribe',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Pi-Audio-Suffix':suffix},body:file});$('notes').value=result.text;noteSource='Transcript: '+file.name;$('local-status').textContent='Transcription complete. Verify names, numbers and medical terms against the recording, then add the notes.';}));
 $('ai-generate').addEventListener('click',safe(async()=>{if(!sources.length)throw new Error('Upload documents or add verified notes/transcripts first.');if(!$('case-label').value.trim()||!$('encounter').value)throw new Error('Enter patient label and encounter first.');if(draft&&!confirm('Replace the current draft with a locally generated draft?'))return;invalidate();const packet=await job('/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({case_label:$('case-label').value,encounter:$('encounter').value,template:templates.find(t=>t.id===$('template').value),sources})});await window.PiIntakeImport(packet);$('local-status').textContent='Draft generated locally. Verify every statement and excerpt before approval.';}));
 $('source-files').addEventListener('change',safe(async()=>{const files=[...$('source-files').files];$('source-files').disabled=true;try{for(const file of files){if(file.size>8*1024*1024)throw new Error('Document size limit: 8 MB.');let pages=[];if(file.name.toLowerCase().endsWith('.txt'))pages=[await file.text()];else if(file.name.toLowerCase().endsWith('.pdf')){const pdfjs=await import('./vendor/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc=PiExtension.runtime.getURL('vendor/pdf.worker.mjs');let pdf;try{pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),isEvalSupported:false,useSystemFonts:false,disableFontFace:true}).promise;if(pdf.numPages>500)throw new Error('Document page limit: 500.');let chars=0;for(let n=1;n<=pdf.numPages;n++){$('result').textContent=`Reading ${file.name}: page ${n}/${pdf.numPages}`;const page=await pdf.getPage(n),text=await page.getTextContent();const content=text.items.filter(i=>typeof i.str==='string').map(i=>i.str+(i.hasEOL?'\n':' ')).join('');chars+=content.length;if(chars>1000000)throw new Error('Document text limit reached.');pages.push(content);}}finally{if(pdf)await pdf.destroy();}}else throw new Error('Choose searchable PDF or TXT documents.');if(!pages.some(p=>p.trim()))throw new Error('No searchable text. This document needs OCR.');add(file.name,pages);}$('result').textContent='Documents loaded locally. Select the report and build a draft.';}finally{$('source-files').disabled=false;$('source-files').value='';}}));
 $('add-notes').addEventListener('click',safe(()=>{const text=$('notes').value.trim();if(!text)throw new Error('Enter notes first.');add(noteSource,[text]);$('notes').value='';noteSource='Doctor notes / transcript';}));
 $('generate').addEventListener('click',safe(()=>{if(!sources.length)throw new Error('Upload documents or add notes first.');if(draft&&!confirm('Replace the current draft and edits using loaded sources?'))return;draft=core.assemble(sources,templates)[$('template').value];invalidate();render();}));
 $('template').addEventListener('change',()=>{invalidate();draft=null;$('draft-fields').replaceChildren();$('draft-status').textContent='Build a draft for this template.';});
 for(const id of ['case-label','encounter'])$(id).addEventListener('input',invalidate);
 $('review-draft').addEventListener('click',safe(()=>{if(!draft)throw new Error('Build or import a draft first.');if(!$('case-label').value.trim()||!$('encounter').value)throw new Error('Enter the patient label and encounter date first.');draft=core.review(draft,$('confirm-review').checked);window.dispatchEvent(new CustomEvent('pi-reviewed',{detail:{case_label:$('case-label').value,encounter:$('encounter').value,report:draft}}));render();}));
 $('copy-draft').addEventListener('click',safe(async()=>{if(!draft)throw new Error('Build a draft first.');const template=templates.find(t=>t.id===draft.template_id);const text=`${draft.status==='reviewed_unsigned'?'Reviewed locally · unsigned':'DRAFT · review required'}\n${$('case-label').value} · ${$('encounter').value}\n\n`+template.fields.map(f=>`${f.label}\n${draft.fields[f.id].text||'[MISSING]'}`).join('\n\n');await navigator.clipboard.writeText(text);$('result').textContent='Report copied. Review before saving in Jane.';}));
 window.PiIntakeImport=async packet=>{await ready;const template=templates.find(t=>t.id===packet?.report?.template_id);if(!template||typeof packet.case_label!=='string')throw new Error('Invalid report template or case label.');const fields={};for(const f of template.fields){const v=packet.report.fields?.[f.id];if(!v||typeof v.text!=='string'||v.text.length>30000)throw new Error('Invalid or oversized report section.');const citations=Array.isArray(v.citations)?v.citations.filter(c=>c&&typeof c.source_name==='string'&&typeof c.quote==='string').map(c=>({source_name:c.source_name,quote:c.quote,page:c.page,line:c.line})):[];fields[f.id]={text:v.text,citations,candidates:[],conflict:false,resolved:false,edited:false};if(v.conflict&&!v.resolved){fields[f.id].text='';fields[f.id].conflict=true;}}draft={template_id:template.id,status:'draft',fields};$('case-label').value=packet.case_label;$('encounter').value=typeof packet.encounter==='string'?packet.encounter:'';$('template').value=template.id;invalidate();render();$('result').textContent='Imported as a draft. Review all sections in this workspace before filling Jane.';};
})();
