(()=>{
 const $=id=>document.getElementById(id);let base='',session='',caseData=null,loaded=null;
 const safe=fn=>async()=>{try{await fn();}catch(e){$('result').textContent=e.message;$('result').className='error';}};
 async function api(path,options={}){const response=await fetch(base+'/api'+path,{...options,headers:{'X-Pi-Session':session,...options.headers}});const value=await response.json();if(!response.ok)throw new Error(value.error||'Workspace request failed');return value;}
 function clear(){loaded=null;window.dispatchEvent(new Event('pi-draft-edited'));}
 async function caseChanged(){clear();caseData=await api('/cases/'+$('shared-case').value);$('shared-report').replaceChildren();const schema=await(await fetch(PiExtension.runtime.getURL('reports.json'))).json();for(const [id,r]of Object.entries(caseData.reports)){if(r.status!=='reviewed_unsigned')continue;const option=document.createElement('option');option.value=id;option.textContent=schema.find(t=>t.id===id)?.title||id;$('shared-report').append(option);}$('shared-load').disabled=!$('shared-report').options.length;$('result').textContent=$('shared-load').disabled?'No approved report for this case. Ask the clinician to review and approve it.':'Select the approved report.';}
 $('shared-login').addEventListener('click',safe(async()=>{
  clear();session='';const url=new URL($('server-url').value.trim());if(url.username||url.password||url.search||url.hash||url.pathname!=='/'||!(url.protocol==='https:'||(url.protocol==='http:'&&url.hostname==='127.0.0.1'&&url.port==='8765')))throw new Error('Use the loopback address or your clinic’s private HTTPS origin.');
  if(url.protocol==='https:'){const allowed=await PiExtension.permissions.request({origins:[url.origin+'/*']});if(!allowed)throw new Error('Workspace site access was not granted.');}
  base=url.origin;const result=await api('/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('shared-user').value,password:$('shared-password').value})});session=result.session;$('shared-password').value='';const cases=await api('/cases');$('shared-case').replaceChildren();for(const c of cases){const o=document.createElement('option');o.value=c.id;o.textContent=`${c.case_label} · ${c.encounter}`;$('shared-case').append(o);}if(cases.length)await caseChanged();else $('result').textContent='No assigned cases yet.';
 }));
 $('shared-case').addEventListener('change',safe(caseChanged));$('shared-report').addEventListener('change',clear);$('server-url').addEventListener('input',()=>{clear();session='';$('shared-load').disabled=true;});
 $('shared-load').addEventListener('click',safe(async()=>{const id=$('shared-case').value,template=$('shared-report').value;const packet=await api('/cases/'+id+'/approved/'+template);loaded={id,template,version:packet.version};window.dispatchEvent(new CustomEvent('pi-reviewed',{detail:packet}));}));
 window.PiBeforeFill=async()=>{if(!loaded)throw new Error('Load an approved report first.');const packet=await api('/cases/'+loaded.id+'/approved/'+loaded.template);if(packet.version!==loaded.version){clear();throw new Error('Case changed after loading. Reload the approved report and remap before filling.');}};
})();
