const $=id=>document.getElementById(id);
let session=null,current=null,templates=[],dirty=false,working=false,generationError='';
const element=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
function message(text,error=false){$('message').textContent=text;$('message').className=error?'error':'';}
const run=fn=>async()=>{try{await fn();}catch(e){message(e.message,true);}};
async function api(path,options={}){const r=await fetch('/api'+path,{...options,headers:{'X-Pi-CSRF':session?.csrf||'',...options.headers}});const v=await r.json();if(!r.ok)throw new Error(v.error||'Request failed');return v;}
const post=(path,value)=>api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});
async function cases(){const list=await api('/cases');$('case-list').replaceChildren();for(const c of list){const b=element('button',`${c.case_label}\n${c.encounter}`);b.addEventListener('click',run(()=>openCase(c.id)));$('case-list').append(b);}}
async function users(){if(session.role!=='clinician')return;const list=await api('/users');$('owner').replaceChildren();for(const u of list){const o=element('option',`${u.name} · ${u.role}`);o.value=u.name;$('owner').append(o);}}
async function signedIn(){templates=await api('/templates');$('login').hidden=true;$('workspace').hidden=false;$('logout').hidden=false;$('identity').textContent=`${session.name} · ${session.role}`;$('owner-label').hidden=$('users-panel').hidden=session.role!=='clinician';$('templates').replaceChildren();for(const t of templates){const label=element('label'),input=element('input');input.type='checkbox';input.value=t.id;input.checked=t.id==='jane_evaluation';label.append(input,document.createTextNode(t.title));$('templates').append(label);}await cases();await users();}
$('signin').addEventListener('click',run(async()=>{session=await post('/login',{name:$('username').value,password:$('password').value});$('password').value='';await signedIn();message('Signed in. Start with a fictional test case.');}));
$('logout').addEventListener('click',run(async()=>{await post('/logout',{});location.reload();}));
$('refresh').addEventListener('click',run(cases));
$('rename-case').addEventListener('click',run(async()=>{if(!leave())return;const label=prompt('Case label (use a de-identified label for this prototype):',current.case_label);if(label===null)return;const encounter=prompt('Date of the evaluation being documented (YYYY-MM-DD):',current.encounter);if(encounter===null)return;current=await post('/cases/'+current.id+'/details',{version:current.version,case_label:label,encounter});await cases();render();message('Case label and encounter updated; uploaded evidence kept.');}));
$('create').addEventListener('click',run(async()=>{if(!leave())return;current=await post('/cases',{case_label:$('case-label').value,encounter:$('encounter').value,owner:session.role==='clinician'?$('owner').value:session.name});await cases();render();}));
$('add-user').addEventListener('click',run(async()=>{await post('/users',{name:$('new-user').value,password:$('new-password').value});$('new-password').value='';await users();message('Worker account created. Share credentials through your established private channel.');}));
function leave(){if(working)throw new Error('Wait for the current job.');return !dirty||confirm('Discard unsaved draft edits?');}
async function openCase(id){if(!leave())return;current=await api('/cases/'+id);render();const health=await api('/health');$('model-status').textContent=health.model_ready?`Local drafting model ready: ${health.model}`:'Ollama model not ready. You can test the saved-case and review workflow using source headings.';}
function render(){generationError='';dirty=false;$('empty').hidden=true;$('case').hidden=false;$('case-title').textContent=current.case_label;$('case-meta').textContent=`Encounter ${current.encounter} · assigned to ${current.owner} · revision ${current.version}`;$('sources').replaceChildren();for(const s of current.sources){const d=element('details'),p=element('pre',s.pages.map((page,i)=>`PAGE ${i+1}\n${page}`).join('\n\n'));const demo=s.demo===true||s.name==='Fictional test evaluation — not a real patient';const excluded=demo||['template','example'].includes(s.kind);const label=element('label'),check=element('input');check.type='checkbox';check.checked=!excluded&&s.included!==false;check.disabled=excluded;label.append(check,document.createTextNode(excluded?'Excluded from AI evidence: demo / template / style example':'Use this source as AI evidence'));check.addEventListener('change',run(async()=>{if(working){check.checked=!check.checked;throw new Error('Wait for the current job.');}if(!leave()){check.checked=!check.checked;return;}current=await post('/cases/'+current.id+'/source_selection',{version:current.version,source_id:s.id,included:check.checked});render();}));d.append(element('summary',`${s.name} · ${s.kind} · ${s.pages.length} page(s)${excluded?' · excluded from AI':''}`),label,p);$('sources').append(d);}$('report-select').replaceChildren();for(const [id,r]of Object.entries(current.reports)){const o=element('option',templates.find(t=>t.id===id).title+' · '+r.status);o.value=id;$('report-select').append(o);}renderReport();api('/cases/'+current.id+'/audit').then(list=>{$('audit').replaceChildren(...list.map(a=>element('p',`${new Date(a.ts*1000).toLocaleString()} · ${a.user} · ${a.action}`)));}).catch(e=>message(e.message,true));}
function renderReport(){current.activeReport=$('report-select').value;dirty=false;$('review-confirm').checked=false;$('report-fields').replaceChildren();const r=current.reports[$('report-select').value];$('save').disabled=$('copy').disabled=!r;$('approve').disabled=!r||session.role!=='clinician';if(!r){$('review-status').textContent=generationError?'GENERATION FAILED · no new report was created. '+generationError:'No reports yet.';return;}$('review-status').textContent=r.status==='reviewed_unsigned'?`Approved by ${r.reviewed_by} · unsigned`:'DRAFT · clinician review required';if(r.generation_method==='local_ai')$('review-status').textContent+=' · generated with local AI';else if(r.generation_method==='source_headings')$('review-status').textContent+=' · heading matcher, no AI';if(Object.values(r.fields).some(v=>v.text.includes('Not documented in this fictional workflow test; clinician completion required.')))$('review-status').textContent+=' · contains fictional test text';if(generationError)$('review-status').textContent='GENERATION FAILED · showing the previous saved report. '+generationError;const t=templates.find(t=>t.id===r.template_id);$('approve').textContent=t.administrative?'Approve unsigned administrative form':'Clinician: approve unsigned draft';if(t.administrative)$('review-status').textContent+=' · administrative form; no signatures or acknowledgments executed';for(const f of t.fields){const v=r.fields[f.id],box=element('div');box.className='field';const label=element('label',f.label),input=element('textarea');input.dataset.field=f.id;input.value=v.text;input.placeholder='Not documented. Enter supported clinician input or explain why this section is not applicable.';input.addEventListener('input',()=>{dirty=true;$('review-confirm').checked=false;$('review-status').textContent='Unsaved edits · approval will be cleared when saved';});label.append(input);box.append(label);if(f.static_text)box.append(element('p','Supplied fixed form wording. Review as an unsigned administrative template.'));if(!v.text){const missing=element('p','Missing source evidence.');missing.className='missing';box.append(missing);}if(v.conflict&&!v.resolved){box.append(element('p','Conflicting sources. Reconcile them before saving and approving.'));for(const candidate of v.candidates||[]){const d=element('details');d.append(element('summary','Conflicting passage'),element('p',candidate.text));box.append(d);}}for(const c of v.citations||[]){const d=element('details'),quote=element('p',c.quote);quote.className='quote';d.append(element('summary',`${c.source_name} · page ${c.page}`),quote);box.append(d);}$('report-fields').append(box);}}
$('report-select').addEventListener('change',()=>{if(dirty&&!confirm('Discard unsaved changes to the previous report?')){const old=current.activeReport;$('report-select').value=old;return;}renderReport();current.activeReport=$('report-select').value;});
async function addSource(source){if(!current)throw new Error('Select a case.');if(!leave())throw new Error('Source not added; unsaved edits were kept.');current=await post('/cases/'+current.id+'/sources',{version:current.version,source});render();message('Source saved. Previous approvals cleared.');}
$('add-source').addEventListener('click',run(async()=>{const text=$('notes').value.trim();if(!text)throw new Error('Enter notes or a verified transcript.');await addSource({name:$('source-title').value||'Evaluation notes',kind:$('kind').value,pages:[text]});$('notes').value='';}));
$('files').addEventListener('change',run(async()=>{const files=[...$('files').files];$('files').disabled=true;try{for(const file of files){if(file.size>8*1024*1024)throw new Error('Document limit: 8 MB.');let pages=[];if(file.name.toLowerCase().endsWith('.txt'))pages=[await file.text()];else if(file.name.toLowerCase().endsWith('.pdf')){const pdfjs=await import('./pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='/pdf.worker.mjs';let pdf;try{pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),isEvalSupported:false,useSystemFonts:false,disableFontFace:true}).promise;if(pdf.numPages>500)throw new Error('Document limit: 500 pages.');for(let n=1;n<=pdf.numPages;n++){message(`Reading ${file.name}: ${n}/${pdf.numPages}`);const p=await pdf.getPage(n),text=await p.getTextContent();pages.push(text.items.filter(i=>typeof i.str==='string').map(i=>i.str+(i.hasEOL?'\n':' ')).join(''));}}finally{await pdf?.destroy();}}else throw new Error('Use searchable PDF or TXT.');if(!pages.some(p=>p.trim()))throw new Error('No searchable text. OCR is needed.');await addSource({name:file.name,kind:$('kind').value,pages});}}finally{$('files').disabled=false;$('files').value='';}}));
async function job(path,options){if(working)throw new Error('A job is running.');working=true;document.querySelectorAll('#report-fields textarea').forEach(e=>e.disabled=true);for(const id of ['generate','match','transcribe','create','fictional','files','add-source','save','approve','report-select','notes','kind','source-title','rename-case'])$(id).disabled=true;try{const {job_id}=await api(path,options);for(;;){await new Promise(r=>setTimeout(r,1200));const j=await api('/jobs/'+job_id);$('job-status').textContent=j.stage||'Working locally';if(j.status==='error')throw new Error(j.error);if(j.status==='complete')return j.result;}}finally{working=false;for(const id of ['generate','match','transcribe','create','fictional','files','add-source','report-select','notes','kind','source-title','rename-case'])$(id).disabled=false;if(current)renderReport();}}
$('transcribe').addEventListener('click',run(async()=>{const file=$('audio').files[0];if(!file)throw new Error('Choose a recording.');if(file.size>100*1024*1024)throw new Error('Audio limit: 100 MB.');if(dirty||$('notes').value.trim())throw new Error('Save edits and add existing notes before transcribing.');const result=await job('/transcribe',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Pi-Audio-Suffix':'.'+file.name.toLowerCase().split('.').pop()},body:file});$('notes').value=result.text;$('source-title').value='Transcript: '+file.name;$('kind').value='transcript';message('Verify transcript against the recording, then add notes.');}));
const selected=()=>[...document.querySelectorAll('#templates input:checked')].map(e=>e.value);
$('generate').addEventListener('click',run(async()=>{if(!leave())return;const ids=selected();if(!ids.length)throw new Error('Select at least one report.');generationError='';$('job-status').textContent='Generating a new draft. The previous saved report is not the new result.';try{if(ids.some(id=>!templates.find(t=>t.id===id)?.administrative)){const health=await api('/health');$('model-status').textContent=health.model_ready?`Local drafting model ready: ${health.model}`:`Local drafting model not ready: ${health.model}`;if(!health.model_ready)throw new Error(`Ollama drafting model ${health.model} is not ready. Transcription can work independently. Start Ollama and install this model before generating.`);}current=await job('/cases/'+current.id+'/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:current.version,templates:ids})});render();$('report-select').value=ids[0];renderReport();const r=current.reports[ids[0]],filled=Object.values(r.fields).filter(f=>f.text.trim()).length,total=Object.keys(r.fields).length;$('job-status').textContent=`Generation complete: ${filled}/${total} sections filled for this report. Missing information stays blank.`;if(filled===0){$('job-status').textContent='No sections filled: the model returned no usable cited content. This does not establish that your documents lack relevant information. Check readable included evidence and case details; extraction or quotation verification may have failed.';message('Empty AI draft: no usable cited content was returned. Do not approve this as a completed report.',true);}else message('New drafts generated and saved from included case evidence. Review the source excerpts.');}catch(e){generationError=e.message;renderReport();$('job-status').textContent='Generation failed: '+e.message+' The previous saved report is still displayed.';throw e;}}));
$('match').addEventListener('click',run(async()=>{if(!leave())return;const result=await post('/cases/'+current.id+'/match',{version:current.version,templates:selected()});current=result;render();message('Heading-matched drafts saved. This tests the workflow without AI interpretation.');}));
$('save').addEventListener('click',run(async()=>{const id=$('report-select').value,fields={};document.querySelectorAll('#report-fields textarea').forEach(e=>fields[e.dataset.field]=e.value);current=await post('/cases/'+current.id+'/reports',{version:current.version,template_id:id,fields});render();$('report-select').value=id;renderReport();message('Draft edits saved; approval cleared.');}));
$('approve').addEventListener('click',run(async()=>{if(dirty)throw new Error('Save draft edits before approval.');const id=$('report-select').value;current=await post('/cases/'+current.id+'/approve',{version:current.version,template_id:id,confirmed:$('review-confirm').checked});render();$('report-select').value=id;renderReport();message('Approved as an unsigned draft. The Jane bridge can now fetch this report directly.');}));
$('copy').addEventListener('click',run(async()=>{if(dirty)throw new Error('Save draft edits first.');const r=current.reports[$('report-select').value],t=templates.find(t=>t.id===r.template_id);await navigator.clipboard.writeText(`${current.case_label} · ${current.encounter}\n${r.status}\n\n`+t.fields.map(f=>`${f.label}\n${r.fields[f.id].text}`).join('\n\n'));message('Report copied.');}));
$('fictional').addEventListener('click',run(async()=>{if(!leave())return;current=await post('/cases',{case_label:'Fictional feasibility patient',encounter:new Date().toLocaleDateString('en-CA'),owner:session.role==='clinician'?$('owner').value:session.name});const t=templates.find(t=>t.id==='jane_evaluation');const text=t.fields.map(f=>`${f.label}: ${f.id==='jane_eval_06'?'Fictional patient reports neck discomfort rated 3/10 after a fictional collision.':f.id==='jane_eval_04'?'Vitals were not supplied in this fictional test.':'Not documented in this fictional workflow test; clinician completion required.'}`).join('\n\n');current=await post('/cases/'+current.id+'/sources',{version:current.version,source:{name:'Fictional test evaluation — not a real patient',kind:'clinical',demo:true,pages:[text]}});current=await post('/cases/'+current.id+'/match',{version:current.version,templates:['jane_evaluation']});await cases();render();message('Fictional case ready. Review the 29-section template; no AI generation was used.');}));
api('/session').then(async value=>{session=value;await signedIn();}).catch(()=>{});
