const $=id=>document.getElementById(id);
let session=null,current=null,templates=[],dirty=false,working=false,generationError='',activeJob=null,pendingExtraction=null;
const element=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
function message(text,error=false){$('message').textContent=text;$('message').className=error?'error':'';}
const run=fn=>async()=>{try{await fn();}catch(e){message(e.message,true);}};
async function api(path,options={}){const r=await fetch('/api'+path,{...options,headers:{'X-Pi-CSRF':session?.csrf||'',...options.headers}});const v=await r.json();if(!r.ok)throw new Error(v.error||'Request failed');return v;}
const post=(path,value)=>api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});
async function cases(){const list=await api('/cases');$('case-list').replaceChildren();for(const c of list){const b=element('button',`${c.case_label}\n${c.encounter}`);b.addEventListener('click',run(()=>openCase(c.id)));$('case-list').append(b);}}
async function users(){if(session.role!=='clinician')return;const list=await api('/users');$('owner').replaceChildren();for(const u of list){const o=element('option',`${u.name} · ${u.role}`);o.value=u.name;$('owner').append(o);}}
async function signedIn(){templates=await api('/templates');$('login').hidden=true;$('workspace').hidden=false;$('logout').hidden=false;$('identity').textContent=`${session.name} · ${session.role}`;$('owner-label').hidden=$('users-panel').hidden=session.role!=='clinician';$('templates').replaceChildren();for(const t of templates){const label=element('label'),input=element('input');input.type='checkbox';input.value=t.id;input.checked=t.id==='jane_evaluation';label.append(input,document.createTextNode(t.title));$('templates').append(label);}await cases();await users();}
$('signin').addEventListener('click',run(async()=>{session=await post('/login',{name:$('username').value,password:$('password').value});$('password').value='';await signedIn();message('Signed in. Start with a fictional test case.');}));
$('logout').addEventListener('click',run(async()=>{await post('/logout',{});location.reload();}));
$('refresh').addEventListener('click',run(cases));
$('rename-case').addEventListener('click',run(async()=>{if(!leave())return;const label=prompt('Case label (use a de-identified label for this prototype):',current.case_label);if(label===null)return;const encounter=prompt('Date of the evaluation being documented (YYYY-MM-DD):',current.encounter);if(encounter===null)return;current=await post('/cases/'+current.id+'/details',{version:current.version,case_label:label,encounter});await cases();render();message('Case label and encounter updated; uploaded evidence kept.');}));
$('create').addEventListener('click',run(async()=>{if(!leave())return;current=await post('/cases',{case_label:$('case-label').value,encounter:$('encounter').value,owner:session.role==='clinician'?$('owner').value:session.name});await cases();render();}));
$('add-user').addEventListener('click',run(async()=>{await post('/users',{name:$('new-user').value,password:$('new-password').value});$('new-password').value='';await users();message('Worker account created. Share credentials through your established private channel.');}));
function leave(){if(working)throw new Error('Wait for the current job.');return !dirty||confirm('Discard unsaved draft edits?');}
async function openCase(id){if(!leave())return;current=await api('/cases/'+id);render();const health=await api('/health');$('model-status').textContent=health.model_ready?`Local drafting model ready: ${health.model}`:'Ollama model not ready. You can test the saved-case and review workflow using source headings.';}
function render(){generationError='';dirty=false;$('empty').hidden=true;$('case').hidden=false;$('case-title').textContent=current.case_label;$('case-meta').textContent=`Encounter ${current.encounter} · assigned to ${current.owner} · revision ${current.version}`;$('sources').replaceChildren();for(const s of current.sources){const d=element('details'),p=element('pre',s.pages.map((page,i)=>`PAGE ${i+1}\n${page}`).join('\n\n'));const demo=s.demo===true||s.name==='Fictional test evaluation — not a real patient';const excluded=demo||['template','example'].includes(s.kind);const label=element('label'),check=element('input');check.type='checkbox';check.checked=!excluded&&s.included!==false;check.disabled=excluded;label.append(check,document.createTextNode(excluded?'Excluded from AI evidence: demo / template / style example':'Use this source as AI evidence'));check.addEventListener('change',run(async()=>{if(working){check.checked=!check.checked;throw new Error('Wait for the current job.');}if(!leave()){check.checked=!check.checked;return;}current=await post('/cases/'+current.id+'/source_selection',{version:current.version,source_id:s.id,included:check.checked});render();}));d.append(element('summary',`${s.name} · ${s.kind} · ${s.pages.length} page(s)${excluded?' · excluded from AI':''}`),label,p);$('sources').append(d);}$('report-select').replaceChildren();for(const [id,r]of Object.entries(current.reports)){const o=element('option',templates.find(t=>t.id===id).title+' · '+r.status);o.value=id;$('report-select').append(o);}renderReport();api('/cases/'+current.id+'/audit').then(list=>{$('audit').replaceChildren(...list.map(a=>element('p',`${new Date(a.ts*1000).toLocaleString()} · ${a.user} · ${a.action}`)));}).catch(e=>message(e.message,true));}
function renderReport(){current.activeReport=$('report-select').value;dirty=false;$('review-confirm').checked=false;$('report-fields').replaceChildren();const r=current.reports[$('report-select').value];$('save').disabled=$('copy').disabled=!r;$('approve').disabled=!r||session.role!=='clinician';if(!r){$('review-status').textContent=generationError?'GENERATION FAILED · no new report was created. '+generationError:'No reports yet.';return;}$('review-status').textContent=r.status==='reviewed_unsigned'?`Approved by ${r.reviewed_by} · unsigned`:'DRAFT · clinician review required';if(r.generation_method==='local_ai')$('review-status').textContent+=' · generated with local AI';else if(r.generation_method==='source_headings')$('review-status').textContent+=' · heading matcher, no AI';if(Object.values(r.fields).some(v=>v.text.includes('Not documented in this fictional workflow test; clinician completion required.')))$('review-status').textContent+=' · contains fictional test text';if(generationError)$('review-status').textContent='GENERATION FAILED · showing the previous saved report. '+generationError;const t=templates.find(t=>t.id===r.template_id);$('approve').textContent=t.administrative?'Approve unsigned administrative form':'Clinician: approve unsigned draft';if(t.administrative)$('review-status').textContent+=' · administrative form; no signatures or acknowledgments executed';for(const f of t.fields){const v=r.fields[f.id],box=element('div');box.className='field';const label=element('label',f.label),input=element('textarea');input.dataset.field=f.id;input.value=v.text;input.placeholder='Not documented. Enter supported clinician input or explain why this section is not applicable.';input.addEventListener('input',()=>{dirty=true;$('review-confirm').checked=false;$('review-status').textContent='Unsaved edits · approval will be cleared when saved';});label.append(input);box.append(label);if(f.static_text)box.append(element('p','Supplied fixed form wording. Review as an unsigned administrative template.'));if(!v.text){const missing=element('p',v.evidence_status==='draft_not_verified'?'The model found excerpts but did not produce a verified draft for this section.':v.evidence_status==='no_verified_excerpts'?'No verified source excerpts were mapped to this section; this may be an extraction or relevance failure.':'Section not populated.');missing.className='missing';box.append(missing);if(v.review_question)box.append(element('p',v.review_question));}if(v.conflict&&!v.resolved){box.append(element('p','Conflicting sources. Reconcile them before saving and approving.'));for(const candidate of v.candidates||[]){const d=element('details');d.append(element('summary','Conflicting passage'),element('p',candidate.text));box.append(d);}}for(const c of v.citations||[]){const d=element('details'),quote=element('p',c.quote);quote.className='quote';d.append(element('summary',`${c.source_name} · page ${c.page}`),quote);box.append(d);}$('report-fields').append(box);}}
$('report-select').addEventListener('change',()=>{if(dirty&&!confirm('Discard unsaved changes to the previous report?')){const old=current.activeReport;$('report-select').value=old;return;}renderReport();current.activeReport=$('report-select').value;});
async function addSource(source){if(!current)throw new Error('Select a case.');if(!leave())throw new Error('Source not added; unsaved edits were kept.');current=await post('/cases/'+current.id+'/sources',{version:current.version,source});render();message('Source saved. Previous approvals cleared.');}
$('add-source').addEventListener('click',run(async()=>{const text=$('notes').value.trim();if(!text)throw new Error('Enter notes or a verified transcript.');await addSource({name:$('source-title').value||'Evaluation notes',kind:$('kind').value,pages:[text]});$('notes').value='';}));
$('files').addEventListener('change',run(async()=>{
 if(!current)throw new Error('Select a case first.');
 if(pendingExtraction)throw new Error('Review or discard the current extraction first.');
 const files=[...$('files').files],caseId=current.id,kind=$('kind').value;
 $('files').disabled=true;
 try{for(const file of files){
  if(file.size>8*1024*1024)throw new Error('Document limit: 8 MB.');
  const pages=[],images=[],uncertainties=[];let visual=false;
  if(file.name.toLowerCase().endsWith('.txt'))pages.push(await file.text());
  else if(file.name.toLowerCase().endsWith('.pdf')){
   const pdfjs=await import('./pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='/pdf.worker.mjs';let pdf;
   try{pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),isEvalSupported:false,useSystemFonts:false,disableFontFace:true}).promise;
    if(pdf.numPages>500)throw new Error('Document limit: 500 pages.');
    for(let n=1;n<=pdf.numPages;n++){
     $('intake-status').textContent=`Reading page ${n}/${pdf.numPages}`;
     const page=await pdf.getPage(n),content=await page.getTextContent();
     let text=content.items.filter(i=>typeof i.str==='string').map(i=>i.str+(i.hasEOL?'\n':' ')).join('');
     if($('visual-mode').checked||text.trim().length<20){
      const health=await api('/health');
      if(!health.vision_ready)throw new Error(`Scanned-page reading needs a local vision model. Run ollama pull ${health.vision_model} in another Terminal window, then upload this file again. No intake evidence was saved.`);
      const base=page.getViewport({scale:1}),viewport=page.getViewport({scale:Math.min(3,1800/Math.max(base.width,base.height))});
      const canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);
      await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;
      const image=canvas.toDataURL('image/png');
      $('intake-status').textContent=`Reading scanned page ${n}/${pdf.numPages} locally`;
      const result=await job('/visual-extract',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:image.split(',')[1]})});
      text=result.text;images[n-1]=image;uncertainties[n-1]=result.uncertainties;visual=true;
     }
     pages.push(text);
    }
   }finally{await pdf?.destroy();}
  }else throw new Error('Upload PDF or TXT using this chooser; use Recording for audio.');
  if(!pages.some(p=>p.trim()))throw new Error('No readable text was extracted.');
  if(current.id!==caseId)throw new Error('The case changed; no extraction was saved.');
  if(visual){
   pendingExtraction={name:file.name,kind,pages,caseId};$('extraction-pages').replaceChildren();
   pages.forEach((text,i)=>{const box=element('div');box.append(element('h3',`Page ${i+1}`));if(images[i]){const image=element('img');image.src=images[i];image.alt=`Original scanned page ${i+1}`;image.style.maxWidth='100%';box.append(image);}if(uncertainties[i]?.length)box.append(element('p','Uncertain answers: '+uncertainties[i].join('; ')));const input=element('textarea');input.rows=12;input.value=text;input.dataset.extractionPage=i;box.append(input);$('extraction-pages').append(box);});
   $('extraction-confirm').checked=false;$('extraction-review').hidden=false;$('intake-status').textContent='Extraction ready for review. It is not saved evidence yet.';break;
  }
  await addSource({name:file.name,kind,pages});$('intake-status').textContent=`Saved readable evidence: ${pages.length} page(s).`;
 }}catch(e){$('intake-status').textContent='Document processing failed: '+e.message;throw e;}finally{$('files').disabled=false;$('files').value='';}
}));
$('discard-extraction').addEventListener('click',()=>{pendingExtraction=null;$('extraction-pages').replaceChildren();$('extraction-review').hidden=true;$('intake-status').textContent='Extraction discarded; no evidence saved.';});
$('save-extraction').addEventListener('click',run(async()=>{if(!pendingExtraction||current.id!==pendingExtraction.caseId)throw new Error('Reopen the case used for extraction.');if(!$('extraction-confirm').checked)throw new Error('Review and confirm the scanned-page answers first.');const {name,kind}=pendingExtraction,pages=[...document.querySelectorAll('[data-extraction-page]')].map(e=>e.value);if(pages.some(p=>!p.trim()))throw new Error('Review each page; explain any unreadable page rather than leaving it empty.');await addSource({name,kind,pages});pendingExtraction=null;$('extraction-review').hidden=true;$('extraction-pages').replaceChildren();$('intake-status').textContent='Verified scanned-page evidence saved. Ready for report generation.';}));
$('cancel-job').addEventListener('click',run(async()=>{if(!activeJob)return;$('cancel-job').disabled=true;await post('/jobs/'+activeJob+'/cancel',{});$('job-status').textContent='Stopping transcription; waiting for the worker to exit.';}));
async function job(path,options){if(working)throw new Error('A job is running.');working=true;document.querySelectorAll('#report-fields textarea').forEach(e=>e.disabled=true);for(const id of ['check-engine','generate','match','transcribe','create','fictional','files','add-source','save','approve','report-select','notes','kind','source-title','rename-case'])$(id).disabled=true;try{const {job_id}=await api(path,options);activeJob=job_id;$('cancel-job').hidden=path!=='/transcribe';$('cancel-job').disabled=false;for(;;){await new Promise(r=>setTimeout(r,1200));const j=await api('/jobs/'+job_id);$('job-status').textContent=(j.stage||'Working locally')+` · ${j.elapsed_seconds||0}s elapsed`;if(path==='/transcribe')$('intake-status').textContent=$('job-status').textContent;if(j.status==='error')throw new Error(j.error);if(j.status==='complete')return j.result;}}finally{activeJob=null;$('cancel-job').hidden=true;working=false;for(const id of ['check-engine','generate','match','transcribe','create','fictional','files','add-source','report-select','notes','kind','source-title','rename-case'])$(id).disabled=false;if(current)renderReport();}}
$('transcribe').addEventListener('click',run(async()=>{const file=$('audio').files[0];if(!file)throw new Error('Choose a recording.');if(file.size>100*1024*1024)throw new Error('Audio limit: 100 MB.');if(dirty||$('notes').value.trim())throw new Error('Save edits and add existing notes before transcribing.');const result=await job('/transcribe',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Pi-Audio-Suffix':'.'+file.name.toLowerCase().split('.').pop()},body:file});$('notes').value=result.text;$('source-title').value='Transcript: '+file.name;$('kind').value='transcript';$('intake-status').textContent='Transcription complete. Review the timestamped text below and add it as evidence.';message('Verify transcript against the recording, then add notes.');}));
const selected=()=>[...document.querySelectorAll('#templates input:checked')].map(e=>e.value);
$('generate').addEventListener('click',run(async()=>{if(!leave())return;if(pendingExtraction)throw new Error('Review and save scanned-page extraction before generating.');const ids=selected();if(!ids.length)throw new Error('Select at least one report.');generationError='';$('job-status').textContent='Generating a new draft. The previous saved report is not the new result.';try{if(ids.some(id=>!templates.find(t=>t.id===id)?.administrative)){const health=await api('/health');$('model-status').textContent=health.model_ready?`Local drafting model ready: ${health.model}`:`Local drafting model not ready: ${health.model}`;if(!health.model_ready)throw new Error(`Ollama drafting model ${health.model} is not ready. Transcription can work independently. Start Ollama and install this model before generating.`);}current=await job('/cases/'+current.id+'/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:current.version,templates:ids})});render();$('report-select').value=ids[0];renderReport();const r=current.reports[ids[0]],filled=Object.values(r.fields).filter(f=>f.text.trim()).length,total=Object.keys(r.fields).length;$('job-status').textContent=`Generation complete: ${filled}/${total} sections filled for this report. Missing information stays blank.`;if(r.performance)$('job-status').textContent+=` Engine v2: ${r.performance.mapping_requests} mapping + ${r.performance.drafting_requests} drafting requests; ${r.performance.cached_mapping_chunks} cached chunks; ${r.performance.elapsed_seconds}s. Format retries may add requests.`;if(filled===0){$('job-status').textContent='No sections filled: the model returned no usable cited content. This does not establish that your documents lack relevant information. Check readable included evidence and case details; extraction or quotation verification may have failed.';message('Empty AI draft: no usable cited content was returned. Do not approve this as a completed report.',true);}else message('New drafts generated and saved from included case evidence. Review the source excerpts.');}catch(e){generationError=e.message;renderReport();$('job-status').textContent='Generation failed: '+e.message+' The previous saved report is still displayed.';throw e;}}));
$('match').addEventListener('click',run(async()=>{if(!leave())return;const result=await post('/cases/'+current.id+'/match',{version:current.version,templates:selected()});current=result;render();message('Heading-matched drafts saved. This tests the workflow without AI interpretation.');}));
$('save').addEventListener('click',run(async()=>{const id=$('report-select').value,fields={};document.querySelectorAll('#report-fields textarea').forEach(e=>fields[e.dataset.field]=e.value);current=await post('/cases/'+current.id+'/reports',{version:current.version,template_id:id,fields});render();$('report-select').value=id;renderReport();message('Draft edits saved; approval cleared.');}));
$('approve').addEventListener('click',run(async()=>{if(dirty)throw new Error('Save draft edits before approval.');const id=$('report-select').value;current=await post('/cases/'+current.id+'/approve',{version:current.version,template_id:id,confirmed:$('review-confirm').checked});render();$('report-select').value=id;renderReport();message('Approved as an unsigned draft. The Jane bridge can now fetch this report directly.');}));
$('copy').addEventListener('click',run(async()=>{if(dirty)throw new Error('Save draft edits first.');const r=current.reports[$('report-select').value],t=templates.find(t=>t.id===r.template_id);await navigator.clipboard.writeText(`${current.case_label} · ${current.encounter}\n${r.status}\n\n`+t.fields.map(f=>`${f.label}\n${r.fields[f.id].text}`).join('\n\n'));message('Report copied.');}));
$('fictional').addEventListener('click',run(async()=>{if(!leave())return;current=await post('/cases',{case_label:'Fictional feasibility patient',encounter:new Date().toLocaleDateString('en-CA'),owner:session.role==='clinician'?$('owner').value:session.name});const t=templates.find(t=>t.id==='jane_evaluation');const text=t.fields.map(f=>`${f.label}: ${f.id==='jane_eval_06'?'Fictional patient reports neck discomfort rated 3/10 after a fictional collision.':f.id==='jane_eval_04'?'Vitals were not supplied in this fictional test.':'Not documented in this fictional workflow test; clinician completion required.'}`).join('\n\n');current=await post('/cases/'+current.id+'/sources',{version:current.version,source:{name:'Fictional test evaluation — not a real patient',kind:'clinical',demo:true,pages:[text]}});current=await post('/cases/'+current.id+'/match',{version:current.version,templates:['jane_evaluation']});await cases();render();message('Fictional case ready. Review the 29-section template; no AI generation was used.');}));
api('/session').then(async value=>{session=value;await signedIn();}).catch(()=>{});

$('check-engine').addEventListener('click',run(async()=>{if(!leave())return;$('engine-status').textContent='Testing model output and citation verification with fictional data; your case will not change.';try{const result=await job('/check-engine',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});$('engine-status').textContent=result.message;}catch(e){$('engine-status').textContent='Engine check failed: '+e.message;throw e;}}));
