const {test,before,after}=require('node:test');const assert=require('node:assert/strict');const {spawn,execFileSync}=require('node:child_process');const {chromium}=require('playwright');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');let server,browser,base,credentials,temp;
before(async()=>{temp=await fs.mkdtemp(path.join(os.tmpdir(),'pi-shared-browser-'));server=spawn('python',['-u','-c',`from pathlib import Path\nimport workspace_server as app\nimport json\np=app.init_store(Path(${JSON.stringify(temp)}))\ns=app.ai.ThreadingHTTPServer(('127.0.0.1',0),app.Handler)\nprint(json.dumps({'port':s.server_port,'credentials':p}),flush=True)\ns.serve_forever()`],{cwd:path.resolve(__dirname,'../local-service'),stdio:['ignore','pipe','ignore']});const value=await new Promise((resolve,reject)=>{server.stdout.once('data',d=>resolve(JSON.parse(d.toString())));server.once('error',reject);});credentials=value.credentials;base='http://127.0.0.1:'+value.port;browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});});
after(async()=>{await browser?.close();server?.kill();await fs.rm(temp,{recursive:true,force:true});});
async function login(name){const context=await browser.newContext(),page=await context.newPage();await page.goto(base);await page.locator('#username').fill(name);await page.locator('#password').fill(credentials[name]);await page.locator('#signin').click();await page.locator('#workspace').waitFor({state:'visible'});return {context,page};}
test('worker prepares the configured chart; clinician approves; reloading retains saved case',async()=>{const {context:wc,page:w}=await login('worker');const {context:cc,page:c}=await login('clinician');try{const errors=[];w.on('pageerror',e=>errors.push(e.message));await w.locator('#fictional').click();await w.locator('#report-fields textarea').first().waitFor();assert.equal(await w.locator('#report-fields textarea').count(),29);assert.equal(await w.locator('#approve').isDisabled(),true);assert.match(await w.locator('#review-status').innerText(),/DRAFT/);await c.locator('#refresh').click();await c.locator('#case-list button').first().click();await c.locator('#report-fields textarea').first().waitFor();await c.locator('#review-confirm').check();await c.locator('#approve').click();await c.waitForFunction(()=>document.getElementById('review-status').textContent.includes('Approved'));await w.reload();await w.locator('#workspace').waitFor({state:'visible'});await w.locator('#case-list button').first().click();await w.locator('#report-fields textarea').first().waitFor();assert.match(await w.locator('#review-status').innerText(),/Approved by clinician/);await w.locator('#report-fields textarea').first().fill('Fictional edited consent documentation.');await w.locator('#save').click();await w.waitForFunction(()=>document.getElementById('review-status').textContent.includes('DRAFT'));assert.deepEqual(errors,[]);}finally{await wc.close();await cc.close();}});
test('searchable PDF uploads into a saved source with page references',async()=>{const {context,page:p}=await login('worker');try{await p.locator('#case-label').fill('Fictional PDF case');await p.locator('#encounter').fill('2026-01-15');await p.locator('#create').click();await p.locator('#case-title').waitFor();const pdf=execFileSync('python',['-c','from reportlab.pdfgen.canvas import Canvas\nfrom io import BytesIO\nimport sys\nb=BytesIO();c=Canvas(b);c.drawString(60,740,"Chief Complaint: Fictional neck discomfort.");c.save();sys.stdout.buffer.write(b.getvalue())']);await p.locator('#files').setInputFiles({name:'fictional.pdf',mimeType:'application/pdf',buffer:pdf});await p.locator('#sources summary').waitFor();assert.match(await p.locator('#sources summary').innerText(),/1 page/);await p.locator('#match').click();await p.locator('#report-fields textarea').first().waitFor();assert.match(await p.locator('#report-fields textarea').nth(5).inputValue(),/Fictional neck discomfort/);}finally{await context.close();}});
test('failed local AI clearly marks the old fictional report instead of presenting it as a new result',async()=>{const {context,page:p}=await login('worker');try{await p.locator('#fictional').click();await p.locator('#report-fields textarea').first().waitFor();await p.route(base+'/api/health',r=>r.fulfill({json:{model_ready:true,model:'qwen3:4b'}}));await p.route(base+'/api/cases/*/generate',r=>r.fulfill({json:{job_id:'failed-test'}}));await p.route(base+'/api/jobs/failed-test',r=>r.fulfill({json:{status:'error',stage:'Extracting evidence',error:'Ollama could not find drafting model qwen3:4b.'}}));await p.locator('#generate').click();await p.waitForFunction(()=>document.getElementById('review-status').textContent.includes('GENERATION FAILED'));assert.match(await p.locator('#job-status').innerText(),/previous saved report/);assert.match(await p.locator('#sources').innerText(),/excluded from AI/);assert.match(await p.locator('#report-fields textarea').first().inputValue(),/fictional workflow test/);}finally{await context.close();}});
test('scanned PDF extraction is reviewed with original image before becoming evidence',async()=>{const {context,page:p}=await login('worker');try{
 await p.locator('#case-label').fill('Fictional scanned intake');await p.locator('#encounter').fill('2026-01-15');await p.locator('#create').click();await p.locator('#case-title').waitFor();
 await p.route(base+'/api/health',r=>r.fulfill({json:{model_ready:true,vision_ready:true,vision_model:'fictional-vision'}}));
 await p.route(base+'/api/visual-extract',async r=>{assert.ok(r.request().postDataJSON().image.length>100);await r.fulfill({json:{job_id:'scan-test'}});});
 await p.route(base+'/api/jobs/scan-test',r=>r.fulfill({json:{status:'complete',result:{text:'Patient marked pain 7/10; neck discomfort.',uncertainties:['Handwriting unclear'],requires_review:true}}}));
 const pdf=execFileSync('python',['-c','from reportlab.pdfgen.canvas import Canvas\nfrom io import BytesIO\nimport sys\nb=BytesIO();c=Canvas(b);c.rect(60,500,80,80);c.showPage();c.save();sys.stdout.buffer.write(b.getvalue())']);
 await p.locator('#files').setInputFiles({name:'fictional-scan.pdf',mimeType:'application/pdf',buffer:pdf});await p.locator('#extraction-review').waitFor({state:'visible'});
 assert.equal(await p.locator('#sources summary').count(),0);assert.equal(await p.locator('#extraction-pages img').count(),1);
 await p.locator('#save-extraction').click();assert.match(await p.locator('#message').innerText(),/confirm/);
 await p.locator('[data-extraction-page]').fill('Verified patient-reported neck pain rated 7/10.');await p.locator('#extraction-confirm').check();await p.locator('#save-extraction').click();await p.locator('#sources summary').waitFor();
 assert.match(await p.locator('#sources pre').textContent(),/Verified patient-reported/);assert.equal(await p.locator('#extraction-review').isHidden(),true);
 }finally{await context.close();}});
test('cancel transcription asks server to stop and restores generation without saving a transcript',async()=>{const {context,page:p}=await login('worker');let canceled=false;try{
 await p.locator('#case-label').fill('Fictional audio cancellation');await p.locator('#encounter').fill('2026-01-15');await p.locator('#create').click();await p.locator('#case-title').waitFor();
 await p.route(base+'/api/transcribe',r=>r.fulfill({json:{job_id:'cancel-test'}}));
 await p.route(base+'/api/jobs/cancel-test',r=>r.fulfill({json:canceled?{status:'error',error:'Transcription canceled. No transcript was saved.'}:{status:'running',stage:'Transcribing: 1.0 of 52.0 recording minutes',elapsed_seconds:10}}));
 await p.route(base+'/api/jobs/cancel-test/cancel',r=>{canceled=true;return r.fulfill({json:{stopping:true}});});
 await p.locator('#audio').setInputFiles({name:'fictional.m4a',mimeType:'audio/mp4',buffer:Buffer.from('fictional audio')});await p.locator('#transcribe').click();await p.locator('#cancel-job').waitFor({state:'visible'});assert.equal(await p.locator('#generate').isDisabled(),true);
 await p.locator('#cancel-job').click();await p.waitForFunction(()=>document.getElementById('message').textContent.includes('canceled'));
 assert.equal(await p.locator('#generate').isDisabled(),false);assert.equal(await p.locator('#notes').inputValue(),'');assert.equal(await p.locator('#sources summary').count(),0);
 }finally{await context.close();}});
test('report engine check reports a fictional result without changing case evidence or reports',async()=>{const {context,page:p}=await login('worker');try{
 await p.locator('#case-label').fill('Fictional engine-check case');await p.locator('#encounter').fill('2026-01-15');await p.locator('#create').click();await p.locator('#case-title').waitFor();
 await p.route(base+'/api/check-engine',r=>r.fulfill({json:{job_id:'engine-test'}}));await p.route(base+'/api/jobs/engine-test',r=>r.fulfill({json:{status:'complete',result:{passed:true,message:'Engine check passed: fictional symptoms produced a cited draft.'}}}));
 await p.locator('#check-engine').click();await p.waitForFunction(()=>document.getElementById('engine-status').textContent.includes('passed'));
 assert.equal(await p.locator('#sources summary').count(),0);assert.equal(await p.locator('#report-select option').count(),0);
 }finally{await context.close();}});
